export enum AccountType {
	GENERAL = 0,
	CASH = 1,
	CURRENT_ACCOUNT = 2,
	CREDIT_CARD = 3,
	SAVING_ACCOUNT = 4,
	BONUS = 5,
	INSURANCE = 6,
	INVESTMENT = 7,
	LOAN = 8,
	MORTGAGE = 9,
	ACCOUNT_WITH_OVERDRAFT = 10,
}
