export const envelopes = {
	"10": {
		id: 10,
		name: "FOOD_AND_DRINKS",
		color: "#f44336",
		localizationString: "cat_group_food_drinks",
		iconName: "restaurant-filled",
		parentId: null,
		app: 0,
	},
	"20": {
		id: 20,
		name: "SHOPPING",
		color: "#4fC3F7",
		localizationString: "cat_group_shopping",
		iconName: "shopping-bag-filled",
		parentId: null,
		app: 0,
	},
	"30": {
		id: 30,
		name: "HOUSING",
		color: "#FFA726",
		localizationString: "cat_group_housing",
		iconName: "exterior-filled",
		parentId: null,
		app: 0,
	},
	"40": {
		id: 40,
		name: "TRANSPORTATION",
		color: "#78909C",
		localizationString: "cat_group_transportation",
		iconName: "bus-filled",
		parentId: null,
		app: 0,
	},
	"50": {
		id: 50,
		name: "VEHICLE",
		color: "#AA00FF",
		localizationString: "cat_group_vehicle",
		iconName: "car-filled",
		parentId: null,
		app: 0,
	},
	"60": {
		id: 60,
		name: "LIFE_ENTERTAINMENT",
		color: "#64DD17",
		localizationString: "cat_group_life_entertainment",
		iconName: "save-the-children-filled",
		parentId: null,
		app: 0,
	},
	"70": {
		id: 70,
		name: "COMMUNICATION_PC",
		color: "#536DFE",
		localizationString: "cat_group_communication_pc",
		iconName: "imac-filled",
		parentId: null,
		app: 0,
	},
	"80": {
		id: 80,
		name: "FINANCIAL_EXPENSES",
		color: "#00BFA5",
		localizationString: "cat_group_financial_expenses",
		iconName: "billing-filled",
		parentId: null,
		app: 0,
	},
	"90": {
		id: 90,
		name: "INVESTMENTS",
		color: "#FF4081",
		localizationString: "cat_group_investments",
		iconName: "crowdfunding-filled",
		parentId: null,
		app: 0,
	},
	"100": {
		id: 100,
		name: "INCOME",
		color: "#FBC02D",
		localizationString: "cat_group_income",
		iconName: "coins-filled",
		parentId: null,
		app: 0,
	},
	"110": {
		id: 110,
		name: "OTHERS",
		color: "#9E9E9E",
		localizationString: "cat_group_others",
		iconName: "menu-filled",
		parentId: null,
		app: 0,
	},
	"130": {
		id: 130,
		name: "UNKNOWN_RECORDS",
		color: "#D0D0D0",
		localizationString: "cat_unknown_records",
		iconName: "question-mark-filled",
		parentId: null,
		app: 0,
	},
	"200": {
		id: 200,
		name: "SYSTEM_CATEGORIES",
		color: "#8BC34A",
		localizationString: "category",
		iconName: "settings-filled",
		parentId: null,
	},
	"210": {
		id: 210,
		name: "VIRTUAL_OTHERS",
		color: "#E91E63",
		localizationString: "miscellaneous",
		iconName: "UNKNOWN_ICON",
		parentId: null,
		app: 0,
	},
	"220": {
		id: 220,
		name: "SAVINGS",
		color: "#9C27B0",
		localizationString: "cat_savings",
		iconName: "money-box-filled",
		parentId: null,
		app: 0,
	},
	"230": {
		id: 230,
		name: "RESERVES",
		color: "#795548",
		localizationString: "cat_reserves",
		iconName: "safe-filled",
		parentId: null,
		app: 0,
	},
	"1000": {
		id: 1000,
		name: "FOOD_AND_DRINKS__GROCERIES",
		color: null,
		localizationString: "cat_sub_group_groceries",
		iconName: "vegetarian-food-filled",
		parentId: 10,
		cardinality: "need",
	},
	"1001": {
		id: 1001,
		name: "FOOD_AND_DRINKS__RESTAURANTS_FAST_FOOD",
		color: null,
		localizationString: "cat_sub_group_restaurant_fast_food",
		iconName: "service-bell-filled",
		parentId: 10,
		cardinality: "want",
	},
	"1002": {
		id: 1002,
		name: "FOOD_AND_DRINKS__BAR_CAFE",
		color: null,
		localizationString: "cat_sub_group_bar_cafe",
		iconName: "bar-filled",
		parentId: 10,
		cardinality: "want",
	},
	"1003": {
		id: 1003,
		name: "FOOD_AND_DRINKS__OTHERS",
		color: null,
		localizationString: "cat_group_food_drinks",
		iconName: "restaurant-filled",
		parentId: 10,
		cardinality: "need",
	},
	"2000": {
		id: 2000,
		name: "SHOPPING__CLOTHES_SHOES",
		color: null,
		localizationString: "cat_sub_group_clothes_shoes",
		iconName: "t-shirt-filled",
		parentId: 20,
		cardinality: "need",
	},
	"2001": {
		id: 2001,
		name: "SHOPPING__JEWELS_ACCESSORIES",
		color: null,
		localizationString: "cat_sub_group_jewels_accessories",
		iconName: "diamond",
		parentId: 20,
		cardinality: "want",
	},
	"2002": {
		id: 2002,
		name: "SHOPPING__HEALTH_BEAUTY",
		color: null,
		localizationString: "cat_sub_group_health_beauty",
		iconName: "cream-tube-filled",
		parentId: 20,
		cardinality: "want",
	},
	"2003": {
		id: 2003,
		name: "SHOPPING__KIDS",
		color: null,
		localizationString: "cat_sub_group_kids",
		iconName: "stroller-filled",
		parentId: 20,
		cardinality: "need",
	},
	"2004": {
		id: 2004,
		name: "SHOPPING__HOME_GARDEN",
		color: null,
		localizationString: "cat_sub_group_home_garden",
		iconName: "bungalow-filled",
		parentId: 20,
		cardinality: "want",
	},
	"2005": {
		id: 2005,
		name: "SHOPPING__PETS_ANIMALS",
		color: null,
		localizationString: "cat_sub_group_pets_animals",
		iconName: "cat-footprint-filled",
		parentId: 20,
		cardinality: "want",
	},
	"2006": {
		id: 2006,
		name: "SHOPPING__ELECTRONICS_ACCESSORIES",
		color: null,
		localizationString: "cat_sub_group_electronics_accessories",
		iconName: "computer-filled",
		parentId: 20,
		cardinality: "want",
	},
	"2007": {
		id: 2007,
		name: "SHOPPING__GIFTS_JOY",
		color: null,
		localizationString: "cat_sub_group_gifts_joy",
		iconName: "gift-filled",
		parentId: 20,
		cardinality: "want",
	},
	"2008": {
		id: 2008,
		name: "SHOPPING__STATIONERY_TOOLS",
		color: null,
		localizationString: "cat_sub_group_stationery_tools",
		iconName: "design-filled",
		parentId: 20,
		cardinality: "want",
	},
	"2009": {
		id: 2009,
		name: "SHOPPING__FREE_TIME",
		color: null,
		localizationString: "cat_sub_group_free_time",
		iconName: "happy-filled",
		parentId: 20,
		cardinality: "want",
	},
	"2010": {
		id: 2010,
		name: "SHOPPING__OTHERS",
		color: null,
		localizationString: "cat_group_shopping",
		iconName: "shopping-bag-filled",
		parentId: 20,
		cardinality: "want",
	},
	"2011": {
		id: 2011,
		name: "SHOPPING__DRUGSTORE",
		color: null,
		localizationString: "cat_sub_group_drugstore",
		iconName: "toothbrush-filled",
		parentId: 20,
		cardinality: "need",
	},
	"3000": {
		id: 3000,
		name: "HOUSING__RENT",
		color: null,
		localizationString: "cat_sub_group_rent",
		iconName: "key-2-filled",
		parentId: 30,
		cardinality: "must",
	},
	"3001": {
		id: 3001,
		name: "HOUSING__MORTGAGE",
		color: null,
		localizationString: "cat_sub_group_mortgage",
		iconName: "sell-property-filled",
		parentId: 30,
		cardinality: "must",
	},
	"3002": {
		id: 3002,
		name: "HOUSING__ENERGY_UTILITIES",
		color: null,
		localizationString: "cat_sub_group_energy_utilities",
		iconName: "idea-filled",
		parentId: 30,
		cardinality: "must",
	},
	"3003": {
		id: 3003,
		name: "HOUSING__SERVICES",
		color: null,
		localizationString: "cat_sub_group_energy_services",
		iconName: "home-automation-filled",
		parentId: 30,
		cardinality: "must",
	},
	"3004": {
		id: 3004,
		name: "HOUSING__MAINTENANCE_REPAIRS",
		color: null,
		localizationString: "cat_sub_group_maintenance_repairs",
		iconName: "hammer-filled",
		parentId: 30,
		cardinality: "need",
	},
	"3005": {
		id: 3005,
		name: "HOUSING__OTHERS",
		color: null,
		localizationString: "cat_group_housing",
		iconName: "exterior-filled",
		parentId: 30,
		cardinality: "must",
	},
	"3010": {
		id: 3010,
		name: "HOUSING__INSURANCE",
		color: null,
		localizationString: "cat_sub_group_property_insurance",
		iconName: "fires-filled",
		parentId: 30,
		cardinality: "need",
	},
	"4000": {
		id: 4000,
		name: "TRANSPORTATION__PUBLIC_TRANSPORT",
		color: null,
		localizationString: "cat_sub_group_public_transport",
		iconName: "tram-filled",
		parentId: 40,
		cardinality: "need",
	},
	"4001": {
		id: 4001,
		name: "TRANSPORTATION__TAXI",
		color: null,
		localizationString: "cat_sub_group_taxi",
		iconName: "taxi-filled",
		parentId: 40,
		cardinality: "want",
	},
	"4002": {
		id: 4002,
		name: "TRANSPORTATION__LONG_DISTANCE",
		color: null,
		localizationString: "cat_sub_group_long_distance",
		iconName: "airplane-mode-on-filled",
		parentId: 40,
		cardinality: "want",
	},
	"4003": {
		id: 4003,
		name: "TRANSPORTATION__BUSINESS_TRIPS",
		color: null,
		localizationString: "cat_sub_group_business_trips",
		iconName: "business-filled",
		parentId: 40,
		cardinality: "need",
	},
	"4004": {
		id: 4004,
		name: "TRANSPORTATION__OTHERS",
		color: null,
		localizationString: "cat_group_transportation",
		iconName: "bus-filled",
		parentId: 40,
		cardinality: "need",
	},
	"5000": {
		id: 5000,
		name: "VEHICLE__FUEL",
		color: null,
		localizationString: "cat_sub_group_fuel",
		iconName: "gas-station-filled",
		parentId: 50,
		cardinality: "need",
	},
	"5001": {
		id: 5001,
		name: "VEHICLE__PARKING",
		color: null,
		localizationString: "cat_sub_group_parking",
		iconName: "parking-filled",
		parentId: 50,
		cardinality: "want",
	},
	"5002": {
		id: 5002,
		name: "VEHICLE__VEHICLE_MAINTENANCE",
		color: null,
		localizationString: "cat_sub_group_vehicle_maintenance",
		iconName: "support-filled",
		parentId: 50,
		cardinality: "need",
	},
	"5003": {
		id: 5003,
		name: "VEHICLE__RENTALS",
		color: null,
		localizationString: "cat_sub_group_rentals",
		iconName: "key-filled",
		parentId: 50,
		cardinality: "want",
	},
	"5004": {
		id: 5004,
		name: "VEHICLE__OTHERS",
		color: null,
		localizationString: "cat_group_vehicle",
		iconName: "car-filled",
		parentId: 50,
		cardinality: "need",
	},
	"5010": {
		id: 5010,
		name: "VEHICLE__INSURANCE",
		color: null,
		localizationString: "cat_sub_group_vehicle_insurance",
		iconName: "car-insurance-card-filled",
		parentId: 50,
		cardinality: "need",
	},
	"6000": {
		id: 6000,
		name: "LIFE_ENTERTAINMENT__HEALTH_CARE_DOCTOR",
		color: null,
		localizationString: "cat_sub_group_health_care_doctor",
		iconName: "doctor-male-filled",
		parentId: 60,
		cardinality: "need",
	},
	"6001": {
		id: 6001,
		name: "LIFE_ENTERTAINMENT__WELLNESS_BEAUTY",
		color: null,
		localizationString: "cat_sub_group_wellness_beauty",
		iconName: "spa-flower-filled",
		parentId: 60,
		cardinality: "want",
	},
	"6002": {
		id: 6002,
		name: "LIFE_ENTERTAINMENT__ACTIVE_SPORT_FITNESS",
		color: null,
		localizationString: "cat_sub_group_active_sport_fitness",
		iconName: "barbell-filled",
		parentId: 60,
		cardinality: "want",
	},
	"6003": {
		id: 6003,
		name: "LIFE_ENTERTAINMENT__CULTURE_SPORT_EVENTS",
		color: null,
		localizationString: "cat_sub_group_culture_sport_events",
		iconName: "applause-filled",
		parentId: 60,
		cardinality: "want",
	},
	"6004": {
		id: 6004,
		name: "LIFE_ENTERTAINMENT__LIFE_EVENTS",
		color: null,
		localizationString: "cat_sub_group_life_events",
		iconName: "birthday-filled",
		parentId: 60,
		cardinality: "want",
	},
	"6005": {
		id: 6005,
		name: "LIFE_ENTERTAINMENT__HOBBIES",
		color: null,
		localizationString: "cat_sub_group_hobbies",
		iconName: "like-filled",
		parentId: 60,
		cardinality: "want",
	},
	"6006": {
		id: 6006,
		name: "LIFE_ENTERTAINMENT__EDUCATION_DEVELOPMENT",
		color: null,
		localizationString: "cat_sub_group_education_development",
		iconName: "student-male-filled",
		parentId: 60,
		cardinality: "need",
	},
	"6007": {
		id: 6007,
		name: "LIFE_ENTERTAINMENT__BOOKS_AUDIO_SUBSCRIPTION",
		color: null,
		localizationString: "cat_sub_group_books_audio_subscription",
		iconName: "bookmark-filled",
		parentId: 60,
		cardinality: "want",
	},
	"6008": {
		id: 6008,
		name: "LIFE_ENTERTAINMENT__TV_STREAMING",
		color: null,
		localizationString: "cat_sub_group_tv_streaming",
		iconName: "retro-tv-filled",
		parentId: 60,
		cardinality: "want",
	},
	"6009": {
		id: 6009,
		name: "LIFE_ENTERTAINMENT__HOLIDAYS_TRIPS_HOTELS",
		color: null,
		localizationString: "cat_sub_group_holiday_trips_hotels",
		iconName: "beach-filled",
		parentId: 60,
		cardinality: "want",
	},
	"6010": {
		id: 6010,
		name: "LIFE_ENTERTAINMENT__CHARITY_GIFTS",
		color: null,
		localizationString: "cat_sub_group_charity_gifts",
		iconName: "gift-filled",
		parentId: 60,
		cardinality: "want",
	},
	"6011": {
		id: 6011,
		name: "LIFE_ENTERTAINMENT__ALCOHOL_TOBACCO",
		color: null,
		localizationString: "cat_sub_group_alcohol_tobacco",
		iconName: "wine-bottle-filled",
		parentId: 60,
		cardinality: "want",
	},
	"6012": {
		id: 6012,
		name: "LIFE_ENTERTAINMENT__LOTTERY_GAMBLING",
		color: null,
		localizationString: "cat_sub_group_lottery_gambling",
		iconName: "dice-filled",
		parentId: 60,
		cardinality: "want",
	},
	"6013": {
		id: 6013,
		name: "LIFE_ENTERTAINMENT__OTHERS",
		color: null,
		localizationString: "cat_group_life_entertainment",
		iconName: "save-the-children-filled",
		parentId: 60,
		cardinality: "want",
	},
	"7001": {
		id: 7001,
		name: "COMMUNICATION_PC__PHONE_CELL_PHONES",
		color: null,
		localizationString: "cat_sub_group_phone_cell_phone",
		iconName: "phone-filled",
		parentId: 70,
		cardinality: "need",
	},
	"7002": {
		id: 7002,
		name: "COMMUNICATION_PC__INTERNET",
		color: null,
		localizationString: "cat_sub_group_internet",
		iconName: "wi-fi-filled",
		parentId: 70,
		cardinality: "need",
	},
	"7003": {
		id: 7003,
		name: "COMMUNICATION_PC__SOFTWARE_APPS_GAMES",
		color: null,
		localizationString: "cat_sub_group_software_apps_games",
		iconName: "software-installer-filled",
		parentId: 70,
		cardinality: "want",
	},
	"7004": {
		id: 7004,
		name: "COMMUNICATION_PC__POSTAL_SERVICES",
		color: null,
		localizationString: "cat_sub_group_postal_services",
		iconName: "message-filled",
		parentId: 70,
		cardinality: "need",
	},
	"7005": {
		id: 7005,
		name: "COMMUNICATION_PC__OTHERS",
		color: null,
		localizationString: "cat_group_communication_pc",
		iconName: "imac-filled",
		parentId: 70,
		cardinality: "need",
	},
	"8000": {
		id: 8000,
		name: "FINANCIAL_EXPENSES__TAXES",
		color: null,
		localizationString: "cat_sub_group_taxes",
		iconName: "tax-filled",
		parentId: 80,
		cardinality: "must",
	},
	"8001": {
		id: 8001,
		name: "FINANCIAL_EXPENSES__INSURANCES",
		color: null,
		localizationString: "cat_sub_group_insurances",
		iconName: "electronic-identity-card-filled",
		parentId: 80,
		cardinality: "need",
	},
	"8002": {
		id: 8002,
		name: "FINANCIAL_EXPENSES__LOAN_INTERESTS",
		color: null,
		localizationString: "cat_sub_group_loan_interests",
		iconName: "money-filled",
		parentId: 80,
		cardinality: "must",
	},
	"8003": {
		id: 8003,
		name: "FINANCIAL_EXPENSES__FINES",
		color: null,
		localizationString: "cat_sub_group_fines",
		iconName: "customs-officer-filled",
		parentId: 80,
		cardinality: "must",
	},
	"8004": {
		id: 8004,
		name: "FINANCIAL_EXPENSES__ADVISORY",
		color: null,
		localizationString: "cat_sub_group_advisory",
		iconName: "voice-presentation-filled",
		parentId: 80,
		cardinality: "want",
	},
	"8005": {
		id: 8005,
		name: "FINANCIAL_EXPENSES__CHARGES_FEES",
		color: null,
		localizationString: "cat_sub_group_charges_fees",
		iconName: "feed-out-filled",
		parentId: 80,
		cardinality: "must",
	},
	"8006": {
		id: 8006,
		name: "VEHICLE__LEASING",
		color: null,
		localizationString: "cat_sub_group_leasing",
		iconName: "expensive-2-filled",
		parentId: 50,
		cardinality: "must",
	},
	"8007": {
		id: 8007,
		name: "FINANCIAL_EXPENSES__ALIMENTS",
		color: null,
		localizationString: "cat_sub_group_aliments",
		iconName: "romper-filled",
		parentId: 80,
		cardinality: "must",
	},
	"8008": {
		id: 8008,
		name: "FINANCIAL_EXPENSES__OTHERS",
		color: null,
		localizationString: "cat_group_financial_expenses",
		iconName: "billing-filled",
		parentId: 80,
		cardinality: "must",
	},
	"9000": {
		id: 9000,
		name: "INVESTMENTS__REALTY",
		color: null,
		localizationString: "cat_sub_group_realty",
		iconName: "apartment-filled",
		parentId: 90,
		cardinality: "want",
	},
	"9001": {
		id: 9001,
		name: "INVESTMENTS__VEHICLES_CHATTELS",
		color: null,
		localizationString: "cat_sub_group_vehicles_chattels",
		iconName: "f1-race-car-side-view-filled",
		parentId: 90,
		cardinality: "want",
	},
	"9002": {
		id: 9002,
		name: "INVESTMENTS__FIN_INVESTMENTS",
		color: null,
		localizationString: "cat_sub_group_financial_investments",
		iconName: "bullish-filled",
		parentId: 90,
		cardinality: "want",
	},
	"9003": {
		id: 9003,
		name: "INVESTMENTS__SAVINGS",
		color: null,
		localizationString: "cat_sub_group_savings",
		iconName: "money-bag-filled",
		parentId: 90,
		cardinality: "want",
	},
	"9004": {
		id: 9004,
		name: "INVESTMENTS__COLLECTIONS",
		color: null,
		localizationString: "cat_sub_group_collections",
		iconName: "collect-filled",
		parentId: 90,
		cardinality: "want",
	},
	"9005": {
		id: 9005,
		name: "INVESTMENTS__OTHERS",
		color: null,
		localizationString: "cat_group_investments",
		iconName: "crowdfunding-filled",
		parentId: 90,
		cardinality: "want",
	},
	"10000": {
		id: 10000,
		name: "INCOME__WAGE_INVOICES",
		color: null,
		localizationString: "cat_sub_group_wage_invoices",
		iconName: "receive-cash-filled",
		parentId: 100,
		cardinality: "want",
	},
	"10001": {
		id: 10001,
		name: "INCOME__INTEREST_DIVIDENDS",
		color: null,
		localizationString: "cat_sub_group_interests_dividends",
		iconName: "loyalty-card-filled",
		parentId: 100,
		cardinality: "want",
	},
	"10002": {
		id: 10002,
		name: "INCOME__SALE",
		color: null,
		localizationString: "cat_sub_group_sale",
		iconName: "move-stock-filled",
		parentId: 100,
		cardinality: "want",
	},
	"10003": {
		id: 10003,
		name: "INCOME__RENTAL_INCOME",
		color: null,
		localizationString: "cat_sub_group_rental_income",
		iconName: "sell-property-filled",
		parentId: 100,
		cardinality: "want",
	},
	"10004": {
		id: 10004,
		name: "INCOME__DUES_GRANTS",
		color: null,
		localizationString: "cat_sub_group_dues_grants",
		iconName: "approval-filled",
		parentId: 100,
		cardinality: "want",
	},
	"10005": {
		id: 10005,
		name: "INCOME__LENDING_RENTING",
		color: null,
		localizationString: "cat_sub_group_lending_renting",
		iconName: "borrow-book-filled",
		parentId: 100,
		cardinality: "want",
	},
	"10006": {
		id: 10006,
		name: "INCOME__CHECKS_COUPONS",
		color: null,
		localizationString: "cat_sub_group_checks_coupons",
		iconName: "check-book-filled",
		parentId: 100,
		cardinality: "want",
	},
	"10007": {
		id: 10007,
		name: "INCOME__LOTTERY_GAMBLING",
		color: null,
		localizationString: "cat_sub_group_lottery_gambling",
		iconName: "dice-filled",
		parentId: 100,
		cardinality: "want",
	},
	"10008": {
		id: 10008,
		name: "INCOME__REFUNDS",
		color: null,
		localizationString: "cat_sub_group_refunds",
		iconName: "return-filled",
		parentId: 100,
		cardinality: "want",
	},
	"10009": {
		id: 10009,
		name: "INCOME__ALIMENTS",
		color: null,
		localizationString: "cat_sub_group_aliments",
		iconName: "romper-filled",
		parentId: 100,
		cardinality: "want",
	},
	"10010": {
		id: 10010,
		name: "INCOME__GIFTS",
		color: null,
		localizationString: "cat_sub_group_gifts",
		iconName: "money-transfer-filled",
		parentId: 100,
		cardinality: "want",
	},
	"10011": {
		id: 10011,
		name: "INCOME__OTHERS",
		color: null,
		localizationString: "cat_group_income",
		iconName: "coins-filled",
		parentId: 100,
		cardinality: "want",
	},
	"11000": {
		id: 11000,
		name: "OTHERS__OTHERS",
		color: null,
		localizationString: "cat_group_others",
		iconName: "menu-filled",
		parentId: 110,
		cardinality: "want",
	},
	"11001": {
		id: 11001,
		name: "OTHERS__MISSING",
		color: null,
		localizationString: "cat_group_missing",
		iconName: "menu-filled",
		parentId: 110,
		cardinality: "want",
	},
	"13000": {
		id: 13000,
		name: "UNKNOWN_RECORDS__INCOME",
		color: null,
		localizationString: "cat_sub_unknown_categories_income",
		iconName: "question-mark-filled",
		parentId: 130,
		cardinality: "want",
	},
	"13001": {
		id: 13001,
		name: "UNKNOWN_RECORDS__EXPENSE",
		color: null,
		localizationString: "cat_sub_unknown_categories_expense",
		iconName: "question-mark-filled",
		parentId: 130,
		cardinality: "want",
	},
	"20000": {
		id: 20000,
		name: "SYSTEM_CATEGORIES_DEBT",
		color: null,
		localizationString: "modules_debts",
		iconName: "money-box-filled",
		parentId: 200,
	},
	"20001": {
		id: 20001,
		name: "SYSTEM_CATEGORIES_TRANSFER",
		color: null,
		localizationString: "transfer_withdraw",
		iconName: "sorting-arrows-horizontal-filled",
		parentId: 200,
	},
	"20002": {
		id: 20002,
		name: "SYSTEM_CATEGORIES_SHOPPING_LIST",
		color: null,
		localizationString: "shopping_list",
		iconName: "shopping-basket-filled",
		parentId: 200,
	},
	"20003": {
		id: 20003,
		name: "SYSTEM_CATEGORIES_UNKNOWN",
		color: null,
		localizationString: "unknown",
		iconName: "question-mark-filled",
		parentId: 200,
	},
	"20004": {
		id: 20004,
		name: "SYSTEM_CATEGORIES_ONE_CLICK_WIDGET",
		color: null,
		localizationString: "oneclick_widget_name",
		iconName: "natural-user-interface-2-filled",
		parentId: 200,
	},
	"20005": {
		id: 20005,
		name: "SYSTEM_CATEGORIES_BANK_STATEMENT",
		color: null,
		localizationString: "bank_parsing_title",
		iconName: "news-filled",
		parentId: 200,
	},
};
